-- #368 (M22) : H_LINE_ACTIVITY_EXECUTION.ITEM_INDEX 추가 (H2)
-- fan-out 레인 인덱스. 비-fan-out/레거시 실행은 0. 기존 행은 DEFAULT 0으로 흡수.
ALTER TABLE H_LINE_ACTIVITY_EXECUTION ADD COLUMN IF NOT EXISTS ITEM_INDEX INT DEFAULT 0 NOT NULL;
