-- #371 (M22) : U_LINE_STATION.STREAM_MODE 추가 (H2)
-- 노드 fan-out 모드 — NONE(기본)/FAN_OUT/COLLECT. 기존 노드는 DEFAULT 'NONE'으로 흡수(동작 무변).
ALTER TABLE U_LINE_STATION ADD COLUMN IF NOT EXISTS STREAM_MODE VARCHAR(20) DEFAULT 'NONE' NOT NULL;
