-- #364 (M22) : U_LINE_STATION PK를 (DEFINITION_ID, ID) composite로 변경 (MariaDB)
-- nodeId(ID)가 라인 간 글로벌 unique이던 함정 제거 — 빌더가 정의마다 n-1,n-2... 재발급해도 충돌 없음.
-- U_LINE_TRACK FK/UNIQUE도 composite로, H_LINE_ACTIVITY_EXECUTION→STATION FK는 제거.
-- U_LINE_INSTANCE에 DEFINITION_ID 추가 — 런타임이 instanceId로 소속 정의를 특정한다.
--
-- 후방 호환: 기존 ID는 이미 글로벌 unique → (DEFINITION_ID, ID)도 자명하게 unique, 데이터 충돌 없음.
-- 1회만 적용. 신규 설치는 schema-mariadb.sql에 이미 반영돼 있다.

-- 1) STATION PK를 참조하던 FK들을 먼저 제거 (PK 변경 전 필수)
ALTER TABLE H_LINE_ACTIVITY_EXECUTION DROP FOREIGN KEY H_LINE_ACTIVITY_EXECUTION_FK02;
ALTER TABLE U_LINE_TRACK DROP FOREIGN KEY U_LINE_TRACK_FK02;
ALTER TABLE U_LINE_TRACK DROP FOREIGN KEY U_LINE_TRACK_FK03;
ALTER TABLE U_LINE_TRACK DROP INDEX U_LINE_TRACK_U01;

-- 2) STATION PK 교체: (ID) → (DEFINITION_ID, ID)
ALTER TABLE U_LINE_STATION DROP PRIMARY KEY;
ALTER TABLE U_LINE_STATION ADD CONSTRAINT U_LINE_STATION_PK PRIMARY KEY (DEFINITION_ID, ID);

-- 2b) TRACK PK 교체: (ID) → (DEFINITION_ID, ID). edgeId도 빌더가 정의마다 e-1,e-2... 재발급되는 동일 함정.
ALTER TABLE U_LINE_TRACK DROP PRIMARY KEY;
ALTER TABLE U_LINE_TRACK ADD CONSTRAINT U_LINE_TRACK_PK PRIMARY KEY (DEFINITION_ID, ID);

-- 3) TRACK FK/UNIQUE를 composite로 재생성 (같은 정의 내 역만 매칭)
ALTER TABLE U_LINE_TRACK ADD CONSTRAINT U_LINE_TRACK_FK02
    FOREIGN KEY (DEFINITION_ID, FROM_NODE_ID) REFERENCES U_LINE_STATION(DEFINITION_ID, ID);
ALTER TABLE U_LINE_TRACK ADD CONSTRAINT U_LINE_TRACK_FK03
    FOREIGN KEY (DEFINITION_ID, TO_NODE_ID) REFERENCES U_LINE_STATION(DEFINITION_ID, ID);
ALTER TABLE U_LINE_TRACK ADD CONSTRAINT U_LINE_TRACK_U01
    UNIQUE (DEFINITION_ID, FROM_NODE_ID, TO_NODE_ID);

-- 4) INSTANCE에 소속 정의 컬럼 추가 (레거시/선형 인스턴스는 NULL)
ALTER TABLE U_LINE_INSTANCE ADD COLUMN IF NOT EXISTS DEFINITION_ID VARCHAR(50) AFTER WORKFLOW_NAME;

-- 5) (선택) 마이그레이션 시점에 RUNNING이던 DAG 인스턴스의 fan-out을 이어가려면 best-effort backfill.
--    WORKFLOW_NAME → 최신 active 정의로 추정. 인스턴스가 실행 중 재버전된 경우엔 부정확할 수 있으니
--    가능하면 in-flight 인스턴스를 drain한 뒤 마이그레이션하는 것을 권장한다.
-- UPDATE U_LINE_INSTANCE i
--   SET i.DEFINITION_ID = (
--     SELECT d.ID FROM U_LINE_DEFINITION d
--      WHERE d.DEFINITION_NM = i.WORKFLOW_NAME AND d.ACTIVE_FL = 'Y' AND d.DEL_FL = 'N'
--      ORDER BY d.VERSION_NO DESC LIMIT 1)
--  WHERE i.DEFINITION_ID IS NULL AND i.STATUS_ST = 'RUNNING';
