-- Drop unused common-column flags USE_FL, VIEW_FL from all U_LINE_* / H_LINE_* tables (MariaDB).
-- 본 두 컬럼은 도입 후 INSERT 'Y' 기본값만 박히고 어디서도 토글/필터되지 않아 dead weight.
-- DEL_FL은 soft-delete로 active 사용 중이라 유지.
-- 자세한 배경은 본 디렉터리의 .md README 참조.

ALTER TABLE U_LINE_INSTANCE              DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE H_LINE_ACTIVITY_EXECUTION    DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE H_LINE_DLQ                   DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_PROJECT               DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_DEFINITION            DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_STATION               DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_TRACK                 DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_SCHEDULE              DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_USER                  DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_USER_ROLE             DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_DEFINITION_ACL        DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;
ALTER TABLE U_LINE_DATASOURCE            DROP COLUMN USE_FL, DROP COLUMN VIEW_FL;

-- U_LINE_USER의 기존 인덱스 (DEL_FL, ENABLED_FL)는 그대로 — USE_FL/VIEW_FL은 인덱스에 포함된 적 없음.
-- U_LINE_DATASOURCE의 (DEL_FL, ENABLED_FL) 인덱스도 동일.
