-- #88 : U_WF_* / H_WF_* → U_LINE_* / H_LINE_* (H2)
-- 자세한 배경/매핑은 본 디렉터리의 README 격 .md 참조.
ALTER TABLE U_WF_DEFINITION           RENAME TO U_LINE_DEFINITION;
ALTER TABLE U_WF_INSTANCE             RENAME TO U_LINE_INSTANCE;
ALTER TABLE U_WF_NODE                 RENAME TO U_LINE_STATION;
ALTER TABLE U_WF_EDGE                 RENAME TO U_LINE_TRACK;
ALTER TABLE U_WF_SCHEDULE             RENAME TO U_LINE_SCHEDULE;
ALTER TABLE H_WF_ACTIVITY_EXECUTION   RENAME TO H_LINE_ACTIVITY_EXECUTION;
ALTER TABLE H_WF_DLQ                  RENAME TO H_LINE_DLQ;
