-- Line Instance Table (Master)
CREATE TABLE U_LINE_INSTANCE (
    ID VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(20) NOT NULL, -- RUNNING, COMPLETED, FAILED, TERMINATED
    INPUT_DATA CLOB, -- JSON format
    OUTPUT_DATA CLOB, -- JSON format
    STATE_DATA CLOB, -- JSON format (Line Context State)
    RUN_OPTIONS CLOB, -- #134: 인스턴스 단위 실행 옵션 JSON
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_INSTANCE_PK PRIMARY KEY (ID)
);

-- Activity Execution Table (History)
-- STATUS_ST: WAITING_DEPENDENCIES, PENDING, RUNNING, COMPLETED, FAILED
-- NODE_ID: DAG 모드에서 U_LINE_STATION 참조. 레거시(선형) 모드에서는 NULL.
CREATE TABLE H_LINE_ACTIVITY_EXECUTION (
    ID VARCHAR2(50),
    INSTANCE_ID VARCHAR2(50) NOT NULL,
    NODE_ID VARCHAR2(50),
    ACTIVITY_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(30) NOT NULL,
    INPUT_DATA CLOB,
    OUTPUT_DATA CLOB,
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT NUMBER DEFAULT 0,
    NEXT_RETRY_DT DATE,
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT H_LINE_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_LINE_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_LINE_INSTANCE(ID)
    -- FK02 (NODE_ID → U_LINE_STATION) 는 U_LINE_STATION 생성 후 파일 끝에서 ALTER TABLE로 추가
);

-- Index for Worker Polling (Oracle/MariaDB)
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX01 ON H_LINE_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX02 ON H_LINE_ACTIVITY_EXECUTION (INSTANCE_ID);
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX03 ON H_LINE_ACTIVITY_EXECUTION (INSTANCE_ID, NODE_ID);

-- Dead Letter Queue Table (History)
CREATE TABLE H_LINE_DLQ (
    ID VARCHAR2(50),
    INSTANCE_ID VARCHAR2(50) NOT NULL,
    EXECUTION_ID VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    ACTIVITY_NAME VARCHAR2(100) NOT NULL,
    DLQ_STATUS_ST VARCHAR2(20) NOT NULL, -- NEW, REQUEUED, DISCARDED
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT NUMBER DEFAULT 0,
    MAX_RETRY_CNT NUMBER,
    FAILED_AT_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT H_LINE_DLQ_PK PRIMARY KEY (ID),
    CONSTRAINT H_LINE_DLQ_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_LINE_INSTANCE(ID),
    CONSTRAINT H_LINE_DLQ_FK02 FOREIGN KEY (EXECUTION_ID) REFERENCES H_LINE_ACTIVITY_EXECUTION(ID)
);

-- Indexes for DLQ (Oracle)
CREATE INDEX H_LINE_DLQ_IDX01 ON H_LINE_DLQ (DLQ_STATUS_ST, REG_DT);
CREATE INDEX H_LINE_DLQ_IDX02 ON H_LINE_DLQ (INSTANCE_ID);

-- ============================================================================
-- DAG Definition Tables (M1-1: 라인을 데이터로 정의)
-- ============================================================================

-- Line Definition Table (Master) - 사용자가 정의한 DAG의 본체
CREATE TABLE U_LINE_DEFINITION (
    ID VARCHAR2(50),
    DEFINITION_NM VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    VERSION_NO NUMBER DEFAULT 1 NOT NULL,
    ACTIVE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SLA_SECONDS NUMBER,                                  -- #138: SLA 시간 임계치 (NULL=비활성)
    SLA_ACTION VARCHAR2(20),                             -- #138: ALERT_ONLY / AUTO_TERMINATE
    CONCURRENCY_POLICY VARCHAR2(20),                     -- #141: CONCURRENT(default) / SKIP_IF_RUNNING
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_DEFINITION_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DEFINITION_U01 UNIQUE (DEFINITION_NM, VERSION_NO)
);

CREATE INDEX U_LINE_DEFINITION_IDX01 ON U_LINE_DEFINITION (ACTIVE_FL, DEL_FL);

-- Line Station Table (Master) - DAG 정의 내 역(=액티비티 호출 단위)
-- DATASOURCE_BINDINGS (#113): JSON map<role,name> — 액티비티가 ``@BoundDataSource("role")``로 참조.
CREATE TABLE U_LINE_STATION (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    NODE_NM VARCHAR2(100),
    ACTIVITY_NM VARCHAR2(100) NOT NULL,
    INPUT_PARAMS CLOB,
    DATASOURCE_BINDINGS CLOB,
    POS_X_NO NUMBER,
    POS_Y_NO NUMBER,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_STATION_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_STATION_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID)
);

CREATE INDEX U_LINE_STATION_IDX01 ON U_LINE_STATION (DEFINITION_ID);
CREATE INDEX U_LINE_STATION_IDX02 ON U_LINE_STATION (ACTIVITY_NM);

-- Line Track Table (Master) - DAG 의존성 (FROM_NODE 완료 후 TO_NODE 활성화)
CREATE TABLE U_LINE_TRACK (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    FROM_NODE_ID VARCHAR2(50) NOT NULL,
    TO_NODE_ID VARCHAR2(50) NOT NULL,
    CONDITION_EXPR VARCHAR2(500),
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_TRACK_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_TRACK_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID),
    CONSTRAINT U_LINE_TRACK_FK02 FOREIGN KEY (FROM_NODE_ID) REFERENCES U_LINE_STATION(ID),
    CONSTRAINT U_LINE_TRACK_FK03 FOREIGN KEY (TO_NODE_ID) REFERENCES U_LINE_STATION(ID),
    CONSTRAINT U_LINE_TRACK_U01 UNIQUE (FROM_NODE_ID, TO_NODE_ID)
);

CREATE INDEX U_LINE_TRACK_IDX01 ON U_LINE_TRACK (DEFINITION_ID);
CREATE INDEX U_LINE_TRACK_IDX02 ON U_LINE_TRACK (FROM_NODE_ID);
CREATE INDEX U_LINE_TRACK_IDX03 ON U_LINE_TRACK (TO_NODE_ID);

-- H_LINE_ACTIVITY_EXECUTION → U_LINE_STATION FK 추가 (U_LINE_STATION 생성 후)
ALTER TABLE H_LINE_ACTIVITY_EXECUTION
    ADD CONSTRAINT H_LINE_ACTIVITY_EXECUTION_FK02 FOREIGN KEY (NODE_ID) REFERENCES U_LINE_STATION(ID);

-- ============================================================================
-- Cron Schedule Table (M2-1: 정기 실행 스케줄)
-- ============================================================================

-- Line Schedule Table (Master) - Oracle
CREATE TABLE U_LINE_SCHEDULE (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    CRON_EXPR VARCHAR2(100) NOT NULL,
    NEXT_RUN_DT DATE,
    LAST_RUN_DT DATE,
    PAUSED_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    INPUT_DATA CLOB,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_SCHEDULE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_SCHEDULE_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID)
);

CREATE INDEX U_LINE_SCHEDULE_IDX01 ON U_LINE_SCHEDULE (PAUSED_FL, NEXT_RUN_DT);
CREATE INDEX U_LINE_SCHEDULE_IDX02 ON U_LINE_SCHEDULE (DEFINITION_ID);

-- ============================================================================
-- Users + Roles (#121) — Spring Security 사용자/역할 테이블
-- ============================================================================

CREATE TABLE U_LINE_USER (
    ID VARCHAR2(50),
    USERNAME VARCHAR2(64) NOT NULL,
    PASSWORD_HASH VARCHAR2(80) NOT NULL,
    DISPLAY_NM VARCHAR2(100),
    ENABLED_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_USER_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_USER_U01 UNIQUE (USERNAME)
);

CREATE INDEX U_LINE_USER_IDX01 ON U_LINE_USER (DEL_FL, ENABLED_FL);

CREATE TABLE U_LINE_USER_ROLE (
    ID VARCHAR2(50),
    USER_ID VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_USER_ROLE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_USER_ROLE_FK01 FOREIGN KEY (USER_ID) REFERENCES U_LINE_USER(ID),
    CONSTRAINT U_LINE_USER_ROLE_U01 UNIQUE (USER_ID, ROLE)
);

CREATE INDEX U_LINE_USER_ROLE_IDX01 ON U_LINE_USER_ROLE (USER_ID);

-- #140 — 라인 정의별 ACL (READ / WRITE / EXECUTE / SCHEDULE / ADMIN).
CREATE TABLE U_LINE_DEFINITION_ACL (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    PERMISSION VARCHAR2(20) NOT NULL,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_DEFINITION_ACL_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DEFINITION_ACL_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID) ON DELETE CASCADE,
    CONSTRAINT U_LINE_DEFINITION_ACL_FK02 FOREIGN KEY (USER_ID) REFERENCES U_LINE_USER(ID) ON DELETE CASCADE,
    CONSTRAINT U_LINE_DEFINITION_ACL_U01 UNIQUE (DEFINITION_ID, USER_ID, PERMISSION)
);
CREATE INDEX U_LINE_DEFINITION_ACL_IDX01 ON U_LINE_DEFINITION_ACL (DEFINITION_ID);
CREATE INDEX U_LINE_DEFINITION_ACL_IDX02 ON U_LINE_DEFINITION_ACL (USER_ID);

-- #142 — 라인 정의 태그 (free-form, many-to-many).
CREATE TABLE U_LINE_DEFINITION_TAG (
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    TAG VARCHAR2(50) NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    CONSTRAINT U_LINE_DEFINITION_TAG_PK PRIMARY KEY (DEFINITION_ID, TAG),
    CONSTRAINT U_LINE_DEFINITION_TAG_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID) ON DELETE CASCADE
);
CREATE INDEX U_LINE_DEFINITION_TAG_IDX01 ON U_LINE_DEFINITION_TAG (TAG);

-- ============================================================================
-- Dynamic DataSource Registry (#110)
-- ============================================================================

-- application.properties의 station8.datasources.* 정적 선언과 별개로, 운영자가
-- 어드민 UI에서 동적으로 추가/수정/제거하는 DataSource 정의 테이블.
-- 이름이 정적 선언과 충돌하면 정적이 win — DB 행은 비활성화 + 무시.
-- 비밀번호는 plain text로 저장 (#112 후속에서 시크릿 통합).
CREATE TABLE U_LINE_DATASOURCE (
    ID VARCHAR2(50),
    NAME VARCHAR2(100) NOT NULL,
    JDBC_URL VARCHAR2(1000) NOT NULL,
    USERNAME VARCHAR2(255),
    PASSWORD VARCHAR2(2000),
    DRIVER_CLASS VARCHAR2(255),
    DIALECT VARCHAR2(50),
    HIKARI_OPTIONS CLOB,
    ENABLED_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_LINE_DATASOURCE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DATASOURCE_U01 UNIQUE (NAME)
);

CREATE INDEX U_LINE_DATASOURCE_IDX01 ON U_LINE_DATASOURCE (DEL_FL, ENABLED_FL);
