-- Line Instance Table (Master) - MariaDB
CREATE TABLE U_LINE_INSTANCE (
    ID VARCHAR(50),
    WORKFLOW_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(20) NOT NULL, -- RUNNING, COMPLETED, FAILED, TERMINATED
    INPUT_DATA LONGTEXT, -- JSON format
    OUTPUT_DATA LONGTEXT, -- JSON format
    STATE_DATA LONGTEXT, -- JSON format (Line Context State)
    RUN_OPTIONS LONGTEXT, -- #134: 인스턴스 단위 실행 옵션 JSON
    START_DT DATETIME,
    END_DT DATETIME,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_INSTANCE_PK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Activity Execution Table (History) - MariaDB
-- STATUS_ST: WAITING_DEPENDENCIES, PENDING, RUNNING, COMPLETED, FAILED
-- NODE_ID: DAG 모드에서 U_LINE_STATION 참조. 레거시(선형) 모드에서는 NULL.
CREATE TABLE H_LINE_ACTIVITY_EXECUTION (
    ID VARCHAR(50),
    INSTANCE_ID VARCHAR(50) NOT NULL,
    NODE_ID VARCHAR(50),
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(30) NOT NULL,
    INPUT_DATA LONGTEXT,
    OUTPUT_DATA LONGTEXT,
    ERROR_MESSAGE LONGTEXT,
    STACK_TRACE LONGTEXT,
    RETRY_CNT INT DEFAULT 0,
    NEXT_RETRY_DT DATETIME,
    START_DT DATETIME,
    END_DT DATETIME,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT H_LINE_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_LINE_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_LINE_INSTANCE(ID)
    -- FK02 (NODE_ID → U_LINE_STATION) 는 U_LINE_STATION 생성 후 파일 끝에서 ALTER TABLE로 추가
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Index for Worker Polling (MariaDB)
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX01 ON H_LINE_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX02 ON H_LINE_ACTIVITY_EXECUTION (INSTANCE_ID);
CREATE INDEX H_LINE_ACTIVITY_EXECUTION_IDX03 ON H_LINE_ACTIVITY_EXECUTION (INSTANCE_ID, NODE_ID);

-- Dead Letter Queue Table (History) - MariaDB
CREATE TABLE H_LINE_DLQ (
    ID VARCHAR(50),
    INSTANCE_ID VARCHAR(50) NOT NULL,
    EXECUTION_ID VARCHAR(50),
    WORKFLOW_NAME VARCHAR(100) NOT NULL,
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    DLQ_STATUS_ST VARCHAR(20) NOT NULL, -- NEW, REQUEUED, DISCARDED
    ERROR_MESSAGE LONGTEXT,
    STACK_TRACE LONGTEXT,
    RETRY_CNT INT DEFAULT 0,
    MAX_RETRY_CNT INT,
    FAILED_AT_DT DATETIME,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT H_LINE_DLQ_PK PRIMARY KEY (ID),
    CONSTRAINT H_LINE_DLQ_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_LINE_INSTANCE(ID),
    CONSTRAINT H_LINE_DLQ_FK02 FOREIGN KEY (EXECUTION_ID) REFERENCES H_LINE_ACTIVITY_EXECUTION(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Indexes for DLQ (MariaDB)
CREATE INDEX H_LINE_DLQ_IDX01 ON H_LINE_DLQ (DLQ_STATUS_ST, REG_DT);
CREATE INDEX H_LINE_DLQ_IDX02 ON H_LINE_DLQ (INSTANCE_ID);

-- ============================================================================
-- DAG Definition Tables (M1-1: 라인을 데이터로 정의)
-- ============================================================================

-- Line Project Table (Master) - MariaDB  #168
-- 라인 정의의 1차 컨테이너. 'default' project가 시드되어 backfill 기본값으로 사용.
CREATE TABLE U_LINE_PROJECT (
    ID VARCHAR(50),
    PROJECT_NM VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_PROJECT_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_PROJECT_U01 UNIQUE (PROJECT_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_PROJECT_IDX01 ON U_LINE_PROJECT (DEL_FL);

-- Line Definition Table (Master) - MariaDB
-- PROJECT_ID (#168): 소속 프로젝트 FK. Seeder가 backfill.
CREATE TABLE U_LINE_DEFINITION (
    ID VARCHAR(50),
    DEFINITION_NM VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    VERSION_NO INT DEFAULT 1 NOT NULL,
    ACTIVE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    SLA_SECONDS BIGINT,                                  -- #138: SLA 시간 임계치 (NULL=비활성)
    SLA_ACTION VARCHAR(20),                              -- #138: ALERT_ONLY / AUTO_TERMINATE
    CONCURRENCY_POLICY VARCHAR(20),                      -- #141: CONCURRENT(default) / SKIP_IF_RUNNING
    PROJECT_ID VARCHAR(50),                              -- #168: 소속 프로젝트 (Seeder가 backfill)
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_DEFINITION_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DEFINITION_U01 UNIQUE (DEFINITION_NM, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- #168: 기존 prod DB 호환 — 컬럼 누락 시 ALTER로 추가. continueOnError로 swallow.
-- IDX02가 PROJECT_ID에 걸리므로 인덱스 생성 전에 컬럼이 존재함을 보장.
ALTER TABLE U_LINE_DEFINITION ADD COLUMN IF NOT EXISTS PROJECT_ID VARCHAR(50);

CREATE INDEX IF NOT EXISTS U_LINE_DEFINITION_IDX01 ON U_LINE_DEFINITION (ACTIVE_FL, DEL_FL);
CREATE INDEX IF NOT EXISTS U_LINE_DEFINITION_IDX02 ON U_LINE_DEFINITION (PROJECT_ID);

-- Line Station Table (Master) - MariaDB
-- DATASOURCE_BINDINGS (#113): JSON map<role,name> — 액티비티가 ``@BoundDataSource("role")``로 참조.
CREATE TABLE U_LINE_STATION (
    ID VARCHAR(50),
    DEFINITION_ID VARCHAR(50) NOT NULL,
    NODE_NM VARCHAR(100),
    ACTIVITY_NM VARCHAR(100) NOT NULL,
    INPUT_PARAMS LONGTEXT,
    DATASOURCE_BINDINGS LONGTEXT,
    POS_X_NO INT,
    POS_Y_NO INT,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_STATION_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_STATION_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_STATION_IDX01 ON U_LINE_STATION (DEFINITION_ID);
CREATE INDEX U_LINE_STATION_IDX02 ON U_LINE_STATION (ACTIVITY_NM);

-- Line Track Table (Master) - MariaDB
CREATE TABLE U_LINE_TRACK (
    ID VARCHAR(50),
    DEFINITION_ID VARCHAR(50) NOT NULL,
    FROM_NODE_ID VARCHAR(50) NOT NULL,
    TO_NODE_ID VARCHAR(50) NOT NULL,
    CONDITION_EXPR VARCHAR(500),
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_TRACK_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_TRACK_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID),
    CONSTRAINT U_LINE_TRACK_FK02 FOREIGN KEY (FROM_NODE_ID) REFERENCES U_LINE_STATION(ID),
    CONSTRAINT U_LINE_TRACK_FK03 FOREIGN KEY (TO_NODE_ID) REFERENCES U_LINE_STATION(ID),
    CONSTRAINT U_LINE_TRACK_U01 UNIQUE (FROM_NODE_ID, TO_NODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_TRACK_IDX01 ON U_LINE_TRACK (DEFINITION_ID);
CREATE INDEX U_LINE_TRACK_IDX02 ON U_LINE_TRACK (FROM_NODE_ID);
CREATE INDEX U_LINE_TRACK_IDX03 ON U_LINE_TRACK (TO_NODE_ID);

-- H_LINE_ACTIVITY_EXECUTION → U_LINE_STATION FK 추가 (U_LINE_STATION 생성 후)
ALTER TABLE H_LINE_ACTIVITY_EXECUTION
    ADD CONSTRAINT H_LINE_ACTIVITY_EXECUTION_FK02 FOREIGN KEY (NODE_ID) REFERENCES U_LINE_STATION(ID);

-- ============================================================================
-- Cron Schedule Table (M2-1: 정기 실행 스케줄)
-- ============================================================================

-- Line Schedule Table (Master) - MariaDB
CREATE TABLE U_LINE_SCHEDULE (
    ID VARCHAR(50),
    DEFINITION_ID VARCHAR(50) NOT NULL,
    CRON_EXPR VARCHAR(100) NOT NULL,
    NEXT_RUN_DT DATETIME,
    LAST_RUN_DT DATETIME,
    PAUSED_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    INPUT_DATA LONGTEXT,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_SCHEDULE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_SCHEDULE_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_SCHEDULE_IDX01 ON U_LINE_SCHEDULE (PAUSED_FL, NEXT_RUN_DT);
CREATE INDEX U_LINE_SCHEDULE_IDX02 ON U_LINE_SCHEDULE (DEFINITION_ID);

-- ============================================================================
-- Users + Roles (#121) — Spring Security 사용자/역할 테이블
-- ============================================================================

CREATE TABLE U_LINE_USER (
    ID VARCHAR(50),
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD_HASH VARCHAR(80) NOT NULL,
    DISPLAY_NM VARCHAR(100),
    ENABLED_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_USER_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_USER_U01 UNIQUE (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_USER_IDX01 ON U_LINE_USER (DEL_FL, ENABLED_FL);

CREATE TABLE U_LINE_USER_ROLE (
    ID VARCHAR(50),
    USER_ID VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_USER_ROLE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_USER_ROLE_FK01 FOREIGN KEY (USER_ID) REFERENCES U_LINE_USER(ID),
    CONSTRAINT U_LINE_USER_ROLE_U01 UNIQUE (USER_ID, ROLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_USER_ROLE_IDX01 ON U_LINE_USER_ROLE (USER_ID);

-- #140 — 라인 정의별 ACL (READ / WRITE / EXECUTE / SCHEDULE / ADMIN).
CREATE TABLE U_LINE_DEFINITION_ACL (
    ID VARCHAR(50),
    DEFINITION_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PERMISSION VARCHAR(20) NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_DEFINITION_ACL_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DEFINITION_ACL_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID) ON DELETE CASCADE,
    CONSTRAINT U_LINE_DEFINITION_ACL_FK02 FOREIGN KEY (USER_ID) REFERENCES U_LINE_USER(ID) ON DELETE CASCADE,
    CONSTRAINT U_LINE_DEFINITION_ACL_U01 UNIQUE (DEFINITION_ID, USER_ID, PERMISSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX U_LINE_DEFINITION_ACL_IDX01 ON U_LINE_DEFINITION_ACL (DEFINITION_ID);
CREATE INDEX U_LINE_DEFINITION_ACL_IDX02 ON U_LINE_DEFINITION_ACL (USER_ID);

-- #142 — 라인 정의 태그 (free-form, many-to-many).
CREATE TABLE U_LINE_DEFINITION_TAG (
    DEFINITION_ID VARCHAR(50) NOT NULL,
    TAG VARCHAR(50) NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    CONSTRAINT U_LINE_DEFINITION_TAG_PK PRIMARY KEY (DEFINITION_ID, TAG),
    CONSTRAINT U_LINE_DEFINITION_TAG_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_LINE_DEFINITION(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX U_LINE_DEFINITION_TAG_IDX01 ON U_LINE_DEFINITION_TAG (TAG);

-- ============================================================================
-- Dynamic DataSource Registry (#110)
-- ============================================================================

-- application.properties의 station8.datasources.* 정적 선언과 별개로, 운영자가
-- 어드민 UI에서 동적으로 추가/수정/제거하는 DataSource 정의 테이블.
-- 이름이 정적 선언과 충돌하면 정적이 win — DB 행은 비활성화 + 무시.
-- 비밀번호는 plain text로 저장 (#112 후속에서 시크릿 통합).
CREATE TABLE U_LINE_DATASOURCE (
    ID VARCHAR(50),
    NAME VARCHAR(100) NOT NULL,
    JDBC_URL VARCHAR(1000) NOT NULL,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(2000),
    DRIVER_CLASS VARCHAR(255),
    DIALECT VARCHAR(50),
    HIKARI_OPTIONS LONGTEXT,
    ENABLED_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_LINE_DATASOURCE_PK PRIMARY KEY (ID),
    CONSTRAINT U_LINE_DATASOURCE_U01 UNIQUE (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX U_LINE_DATASOURCE_IDX01 ON U_LINE_DATASOURCE (DEL_FL, ENABLED_FL);
