spring.datasource.url=jdbc:mariadb://localhost:3307/workflow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=wfuser
spring.datasource.password=wfpw
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.sql.init.mode=never

# JPA is not used; we rely on JdbcTemplate
spring.jpa.show-sql=false
