-- Migration Test Tables
-- Source Table (Oracle Simulation)
CREATE TABLE SRC_DATA (
    ID VARCHAR(36) PRIMARY KEY,
    CONTENT VARCHAR(255),
    MIGRATED_FL CHAR(1) DEFAULT 'N',
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Target Table (MariaDB Simulation)
CREATE TABLE DEST_DATA (
    ID VARCHAR(36) PRIMARY KEY,
    CONTENT VARCHAR(255),
    MIGRATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample Data
INSERT INTO SRC_DATA (ID, CONTENT) VALUES ('1', 'First Data');
INSERT INTO SRC_DATA (ID, CONTENT) VALUES ('2', 'Second Data');
INSERT INTO SRC_DATA (ID, CONTENT) VALUES ('3', 'Third Data');
