-- Workflow Instance Table (Master)
CREATE TABLE U_WF_INSTANCE (
    ID VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(20) NOT NULL, -- RUNNING, COMPLETED, FAILED, TERMINATED
    INPUT_DATA CLOB, -- JSON format
    OUTPUT_DATA CLOB, -- JSON format
    STATE_DATA CLOB, -- JSON format (Workflow Context State)
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_WF_INSTANCE_PK PRIMARY KEY (ID)
);

-- Activity Execution Table (History)
-- STATUS_ST: WAITING_DEPENDENCIES, PENDING, RUNNING, COMPLETED, FAILED
-- NODE_ID: DAG 모드에서 U_WF_NODE 참조. 레거시(선형) 모드에서는 NULL.
CREATE TABLE H_WF_ACTIVITY_EXECUTION (
    ID VARCHAR2(50),
    INSTANCE_ID VARCHAR2(50) NOT NULL,
    NODE_ID VARCHAR2(50),
    ACTIVITY_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(30) NOT NULL,
    INPUT_DATA CLOB,
    OUTPUT_DATA CLOB,
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT NUMBER DEFAULT 0,
    NEXT_RETRY_DT DATE,
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID)
    -- FK02 (NODE_ID → U_WF_NODE) 는 U_WF_NODE 생성 후 파일 끝에서 ALTER TABLE로 추가
);

-- Index for Worker Polling (Oracle/MariaDB)
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX01 ON H_WF_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX02 ON H_WF_ACTIVITY_EXECUTION (INSTANCE_ID);
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX03 ON H_WF_ACTIVITY_EXECUTION (INSTANCE_ID, NODE_ID);

-- Dead Letter Queue Table (History)
CREATE TABLE H_WF_DLQ (
    ID VARCHAR2(50),
    INSTANCE_ID VARCHAR2(50) NOT NULL,
    EXECUTION_ID VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    ACTIVITY_NAME VARCHAR2(100) NOT NULL,
    DLQ_STATUS_ST VARCHAR2(20) NOT NULL, -- NEW, REQUEUED, DISCARDED
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT NUMBER DEFAULT 0,
    MAX_RETRY_CNT NUMBER,
    FAILED_AT_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT H_WF_DLQ_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_DLQ_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID),
    CONSTRAINT H_WF_DLQ_FK02 FOREIGN KEY (EXECUTION_ID) REFERENCES H_WF_ACTIVITY_EXECUTION(ID)
);

-- Indexes for DLQ (Oracle)
CREATE INDEX H_WF_DLQ_IDX01 ON H_WF_DLQ (DLQ_STATUS_ST, REG_DT);
CREATE INDEX H_WF_DLQ_IDX02 ON H_WF_DLQ (INSTANCE_ID);

-- ============================================================================
-- DAG Definition Tables (M1-1: 워크플로우를 데이터로 정의)
-- ============================================================================

-- Workflow Definition Table (Master) - 사용자가 정의한 DAG의 본체
CREATE TABLE U_WF_DEFINITION (
    ID VARCHAR2(50),
    DEFINITION_NM VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    VERSION_NO NUMBER DEFAULT 1 NOT NULL,
    ACTIVE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_WF_DEFINITION_PK PRIMARY KEY (ID),
    CONSTRAINT U_WF_DEFINITION_U01 UNIQUE (DEFINITION_NM, VERSION_NO)
);

CREATE INDEX U_WF_DEFINITION_IDX01 ON U_WF_DEFINITION (ACTIVE_FL, DEL_FL);

-- Workflow Node Table (Master) - DAG 정의 내 노드(=액티비티 호출 단위)
CREATE TABLE U_WF_NODE (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    NODE_NM VARCHAR2(100),
    ACTIVITY_NM VARCHAR2(100) NOT NULL,
    INPUT_PARAMS CLOB,
    POS_X_NO NUMBER,
    POS_Y_NO NUMBER,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_WF_NODE_PK PRIMARY KEY (ID),
    CONSTRAINT U_WF_NODE_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_WF_DEFINITION(ID)
);

CREATE INDEX U_WF_NODE_IDX01 ON U_WF_NODE (DEFINITION_ID);
CREATE INDEX U_WF_NODE_IDX02 ON U_WF_NODE (ACTIVITY_NM);

-- Workflow Edge Table (Master) - DAG 의존성 (FROM_NODE 완료 후 TO_NODE 활성화)
CREATE TABLE U_WF_EDGE (
    ID VARCHAR2(50),
    DEFINITION_ID VARCHAR2(50) NOT NULL,
    FROM_NODE_ID VARCHAR2(50) NOT NULL,
    TO_NODE_ID VARCHAR2(50) NOT NULL,
    CONDITION_EXPR VARCHAR2(500),
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_WF_EDGE_PK PRIMARY KEY (ID),
    CONSTRAINT U_WF_EDGE_FK01 FOREIGN KEY (DEFINITION_ID) REFERENCES U_WF_DEFINITION(ID),
    CONSTRAINT U_WF_EDGE_FK02 FOREIGN KEY (FROM_NODE_ID) REFERENCES U_WF_NODE(ID),
    CONSTRAINT U_WF_EDGE_FK03 FOREIGN KEY (TO_NODE_ID) REFERENCES U_WF_NODE(ID),
    CONSTRAINT U_WF_EDGE_U01 UNIQUE (FROM_NODE_ID, TO_NODE_ID)
);

CREATE INDEX U_WF_EDGE_IDX01 ON U_WF_EDGE (DEFINITION_ID);
CREATE INDEX U_WF_EDGE_IDX02 ON U_WF_EDGE (FROM_NODE_ID);
CREATE INDEX U_WF_EDGE_IDX03 ON U_WF_EDGE (TO_NODE_ID);

-- H_WF_ACTIVITY_EXECUTION → U_WF_NODE FK 추가 (U_WF_NODE 생성 후)
ALTER TABLE H_WF_ACTIVITY_EXECUTION
    ADD CONSTRAINT H_WF_ACTIVITY_EXECUTION_FK02 FOREIGN KEY (NODE_ID) REFERENCES U_WF_NODE(ID);
