-- Workflow Instance Table (Master) - H2
CREATE TABLE IF NOT EXISTS U_WF_INSTANCE (
    ID VARCHAR(50),
    WORKFLOW_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(20) NOT NULL,
    INPUT_DATA CLOB,
    OUTPUT_DATA CLOB,
    STATE_DATA CLOB,
    START_DT TIMESTAMP,
    END_DT TIMESTAMP,
    USE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT TIMESTAMP,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_WF_INSTANCE_PK PRIMARY KEY (ID)
);

-- Activity Execution Table (History) - H2
CREATE TABLE IF NOT EXISTS H_WF_ACTIVITY_EXECUTION (
    ID VARCHAR(50),
    INSTANCE_ID VARCHAR(50) NOT NULL,
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(20) NOT NULL,
    INPUT_DATA CLOB,
    OUTPUT_DATA CLOB,
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT INT DEFAULT 0,
    NEXT_RETRY_DT TIMESTAMP,
    START_DT TIMESTAMP,
    END_DT TIMESTAMP,
    USE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT TIMESTAMP,
    EDIT_ID VARCHAR(32),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID)
);

CREATE INDEX IF NOT EXISTS H_WF_ACTIVITY_EXECUTION_IDX01 ON H_WF_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX IF NOT EXISTS H_WF_ACTIVITY_EXECUTION_IDX02 ON H_WF_ACTIVITY_EXECUTION (INSTANCE_ID);

-- Dead Letter Queue Table (History) - H2
CREATE TABLE IF NOT EXISTS H_WF_DLQ (
    ID VARCHAR(50),
    INSTANCE_ID VARCHAR(50) NOT NULL,
    EXECUTION_ID VARCHAR(50),
    WORKFLOW_NAME VARCHAR(100) NOT NULL,
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    DLQ_STATUS_ST VARCHAR(20) NOT NULL,
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT INT DEFAULT 0,
    MAX_RETRY_CNT INT,
    FAILED_AT_DT TIMESTAMP,
    USE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT TIMESTAMP,
    EDIT_ID VARCHAR(32),
    CONSTRAINT H_WF_DLQ_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_DLQ_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID),
    CONSTRAINT H_WF_DLQ_FK02 FOREIGN KEY (EXECUTION_ID) REFERENCES H_WF_ACTIVITY_EXECUTION(ID)
);

CREATE INDEX IF NOT EXISTS H_WF_DLQ_IDX01 ON H_WF_DLQ (DLQ_STATUS_ST, REG_DT);
CREATE INDEX IF NOT EXISTS H_WF_DLQ_IDX02 ON H_WF_DLQ (INSTANCE_ID);
