-- Workflow Instance Table (Master) - MariaDB
CREATE TABLE U_WF_INSTANCE (
    ID VARCHAR(50),
    WORKFLOW_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(20) NOT NULL, -- RUNNING, COMPLETED, FAILED, TERMINATED
    INPUT_DATA LONGTEXT, -- JSON format
    OUTPUT_DATA LONGTEXT, -- JSON format
    STATE_DATA LONGTEXT, -- JSON format (Workflow Context State)
    START_DT DATETIME,
    END_DT DATETIME,
    USE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT U_WF_INSTANCE_PK PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Activity Execution Table (History) - MariaDB
CREATE TABLE H_WF_ACTIVITY_EXECUTION (
    ID VARCHAR(50),
    INSTANCE_ID VARCHAR(50) NOT NULL,
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    STATUS_ST VARCHAR(20) NOT NULL, -- PENDING, RUNNING, COMPLETED, FAILED
    INPUT_DATA LONGTEXT,
    OUTPUT_DATA LONGTEXT,
    ERROR_MESSAGE LONGTEXT,
    STACK_TRACE LONGTEXT,
    RETRY_CNT INT DEFAULT 0,
    NEXT_RETRY_DT DATETIME,
    START_DT DATETIME,
    END_DT DATETIME,
    USE_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR(1) DEFAULT 'N' NOT NULL,
    REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(32),
    EDIT_DT DATETIME,
    EDIT_ID VARCHAR(32),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Index for Worker Polling (MariaDB)
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX01 ON H_WF_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX02 ON H_WF_ACTIVITY_EXECUTION (INSTANCE_ID);
