-- Workflow Instance Table (Master)
CREATE TABLE U_WF_INSTANCE (
    ID VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(20) NOT NULL, -- RUNNING, COMPLETED, FAILED, TERMINATED
    INPUT_DATA CLOB, -- JSON format
    OUTPUT_DATA CLOB, -- JSON format
    STATE_DATA CLOB, -- JSON format (Workflow Context State)
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT U_WF_INSTANCE_PK PRIMARY KEY (ID)
);

-- Activity Execution Table (History)
CREATE TABLE H_WF_ACTIVITY_EXECUTION (
    ID VARCHAR2(50),
    INSTANCE_ID VARCHAR2(50) NOT NULL,
    ACTIVITY_NAME VARCHAR2(100) NOT NULL,
    STATUS_ST VARCHAR2(20) NOT NULL, -- PENDING, RUNNING, COMPLETED, FAILED
    INPUT_DATA CLOB,
    OUTPUT_DATA CLOB,
    ERROR_MESSAGE CLOB,
    STACK_TRACE CLOB,
    RETRY_CNT NUMBER DEFAULT 0,
    NEXT_RETRY_DT DATE,
    START_DT DATE,
    END_DT DATE,
    USE_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    VIEW_FL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_FL VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_DT DATE DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR2(32),
    EDIT_DT DATE,
    EDIT_ID VARCHAR2(32),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_PK PRIMARY KEY (ID),
    CONSTRAINT H_WF_ACTIVITY_EXECUTION_FK01 FOREIGN KEY (INSTANCE_ID) REFERENCES U_WF_INSTANCE(ID)
);

-- Index for Worker Polling (Oracle/MariaDB)
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX01 ON H_WF_ACTIVITY_EXECUTION (STATUS_ST, NEXT_RETRY_DT);
CREATE INDEX H_WF_ACTIVITY_EXECUTION_IDX02 ON H_WF_ACTIVITY_EXECUTION (INSTANCE_ID);
